name: dart_utils
description: A new Flutter package project.
version: 0.0.1
# homepage:

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  path: ^1.8.2
  intl: ^0.18.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
